'use client';
import { useEffect, useRef, useState } from 'react';
import { PIXEL_CANDLESTICK_CHART_HTML } from './PixelCandlestickChart-dom';

// AUTO-GENERATED by cloner/src/lib/pixel_render_clone.mjs.
// Captured HTML lives in ./PixelCandlestickChart-dom.ts.
// Source URI: requested-0f055.html @ WIDGET_TYPE_CHART
// Render-to-match pattern: production CSS styles production DOM, so we
// inject it via innerHTML once (NOT dangerouslySetInnerHTML, which would
// blow away anything we mount inside the subtree on every re-render).

type Props = {
  onComparisons?: () => void;
  onIndicators?: () => void;
  onLockScale?: () => void;
};

export function PixelCandlestickChart(props: Props) {
  const {
    onComparisons,
    onIndicators,
    onLockScale,
  } = props;
  const rootRef = useRef<HTMLDivElement | null>(null);
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const [domReady, setDomReady] = useState(false);

  // Inject the captured DOM exactly once.
  useEffect(() => {
    if (!rootRef.current) return;
    if (rootRef.current.innerHTML === '') {
      rootRef.current.innerHTML = PIXEL_CANDLESTICK_CHART_HTML;
    }
    setDomReady(true);
  }, []);

  // Optional canvas mount: inject a <canvas> inside the captured DOM at the
  // configured selector. Re-mounts on prop changes that would re-run this
  // effect (none by default). Consumers can grab canvasRef.current to draw.
  useEffect(() => {
    if (!domReady || !rootRef.current) return;
    const area = rootRef.current.querySelector<HTMLElement>("[data-element=\"canvasArea\"]");
    if (!area) return;

    // The captured chartResizer/Container/canvasArea inherit height from their
    // grandparent which our preview doesn't fully reproduce. Force the chart
    // chain to flex-fill so the canvas gets real height.
    const ladderTimeout = rootRef.current.querySelector<HTMLElement>('[data-testid="ladder-timeout-wrapper"]');
    if (ladderTimeout) ladderTimeout.style.flex = '1 1 auto';
    [
      '[data-element="chartResizer"]',
      '[data-element="chartContainer"]',
      '[data-element="canvasArea"]',
    ].forEach((sel) => {
      const el = rootRef.current!.querySelector<HTMLElement>(sel);
      if (el) {
        el.style.height = '100%';
        el.style.width = '100%';
        el.style.minHeight = '300px';
      }
    });
    // Also ensure the chart's relative ancestor expands
    const chartArea = rootRef.current.querySelector<HTMLElement>('.chartArea--graph');
    if (chartArea) chartArea.style.minHeight = '300px';

    const canvas = document.createElement('canvas');
    canvas.style.position = 'absolute';
    canvas.style.inset = '0';
    canvas.style.width = '100%';
    canvas.style.height = '100%';
    canvas.style.touchAction = 'manipulation';
    area.appendChild(canvas);
    canvasRef.current = canvas;

    // Draw candles + volume on the canvas. We render real-looking OHLC data
    // anchored at the captured Close = 62.95 (AMD 5/8 $392.5 Call last trade).
    const draw = () => {
      const rect = canvas.getBoundingClientRect();
      const dpr = window.devicePixelRatio || 1;
      canvas.width = rect.width * dpr;
      canvas.height = rect.height * dpr;
      const ctx = canvas.getContext('2d');
      if (!ctx) return;
      ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
      ctx.clearRect(0, 0, rect.width, rect.height);

      // Generate ~80 deterministic candles ending near close=62.95
      const N = 80;
      const seed = 42;
      let rng = seed;
      const rand = () => { rng = (rng * 9301 + 49297) % 233280; return rng / 233280; };
      let price = 18.5;
      const candles: { o: number; h: number; l: number; c: number; v: number }[] = [];
      for (let i = 0; i < N; i++) {
        const drift = (62.95 - price) / Math.max(1, N - i) * 0.6;
        const vol = 0.6 + rand() * 1.2;
        const o = price;
        const c = price + drift + (rand() - 0.5) * vol;
        const h = Math.max(o, c) + rand() * vol * 0.8;
        const l = Math.min(o, c) - rand() * vol * 0.8;
        candles.push({ o, h, l, c, v: 8 + Math.floor(rand() * 40 + Math.abs(c - o) * 20) });
        price = c;
      }
      // Force the very last candle to match the captured OHLC
      candles[N - 1] = { o: 61.85, h: 63.30, l: 61.75, c: 62.95, v: 38 };

      const minP = Math.min(...candles.map(c => c.l));
      const maxP = Math.max(...candles.map(c => c.h));
      const padTop = 12;
      const volH = Math.max(60, rect.height * 0.18);
      const priceH = rect.height - volH - padTop - 8;
      const rightScaleW = 60;
      const chartW = rect.width - rightScaleW;
      const candleW = Math.max(3, (chartW - 8) / N - 1);
      const POSITIVE = '#00C805';
      const NEGATIVE = '#FF5000';
      const FG3 = 'rgba(255,255,255,0.4)';

      const yForPrice = (p: number) => padTop + (1 - (p - minP) / (maxP - minP)) * priceH;

      // Horizontal grid lines
      ctx.strokeStyle = 'rgba(255,255,255,0.04)';
      ctx.lineWidth = 1;
      for (let i = 0; i <= 5; i++) {
        const y = padTop + (priceH / 5) * i;
        ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(chartW, y); ctx.stroke();
      }

      // Candles
      candles.forEach((c, i) => {
        const x = 4 + i * (candleW + 1);
        const up = c.c >= c.o;
        const color = up ? POSITIVE : NEGATIVE;
        const yO = yForPrice(c.o), yC = yForPrice(c.c), yH = yForPrice(c.h), yL = yForPrice(c.l);
        ctx.strokeStyle = color;
        ctx.lineWidth = 1;
        ctx.beginPath(); ctx.moveTo(x + candleW / 2, yH); ctx.lineTo(x + candleW / 2, yL); ctx.stroke();
        ctx.fillStyle = color;
        const bodyTop = Math.min(yO, yC);
        const bodyH = Math.max(1, Math.abs(yC - yO));
        ctx.fillRect(x, bodyTop, candleW, bodyH);
      });

      // Volume bars
      const maxV = Math.max(...candles.map(c => c.v));
      const volBase = padTop + priceH + 8 + volH;
      candles.forEach((c, i) => {
        const x = 4 + i * (candleW + 1);
        const up = c.c >= c.o;
        ctx.fillStyle = (up ? POSITIVE : NEGATIVE) + '99';
        const h = (c.v / maxV) * (volH - 4);
        ctx.fillRect(x, volBase - h, candleW, h);
      });

      // Right price scale labels
      ctx.fillStyle = FG3;
      ctx.font = '11px Phonic, ui-monospace, monospace';
      ctx.textAlign = 'left';
      ctx.textBaseline = 'middle';
      for (let i = 0; i <= 5; i++) {
        const p = maxP - ((maxP - minP) / 5) * i;
        const y = padTop + (priceH / 5) * i;
        ctx.fillText(`$${p.toFixed(2)}`, chartW + 8, y);
      }

      // Last-price pill on the right side
      const last = candles[N - 1].c;
      const lastY = yForPrice(last);
      ctx.fillStyle = POSITIVE;
      ctx.fillRect(chartW + 4, lastY - 9, rightScaleW - 8, 18);
      ctx.fillStyle = '#fff';
      ctx.font = '700 11px Phonic, ui-monospace, monospace';
      ctx.textAlign = 'center';
      ctx.textBaseline = 'middle';
      ctx.fillText(`$${last.toFixed(2)}`, chartW + 4 + (rightScaleW - 8) / 2, lastY);

      // Dashed line at last price
      ctx.strokeStyle = POSITIVE + '99';
      ctx.setLineDash([4, 4]);
      ctx.beginPath();
      ctx.moveTo(0, lastY);
      ctx.lineTo(chartW, lastY);
      ctx.stroke();
      ctx.setLineDash([]);
    };

    draw();
    const ro = new ResizeObserver(draw);
    ro.observe(canvas);
    return () => {
      ro.disconnect();
      canvas.remove();
      canvasRef.current = null;
    };
  }, [domReady]);
  // Interactivity: onComparisons -> testid="comparisons_menu_button" (click)
  useEffect(() => {
    if (!domReady) return;
    const root = rootRef.current;
    if (!root) return;
    const el = root.querySelector<HTMLButtonElement>("[data-testid='comparisons_menu_button']");
    if (!el) return;
    const handler = () => onComparisons?.();
    el.addEventListener('click', handler);
    return () => el.removeEventListener('click', handler);
  }, [domReady, onComparisons]);

  // Interactivity: onIndicators -> testid="indicators_menu_button" (click)
  useEffect(() => {
    if (!domReady) return;
    const root = rootRef.current;
    if (!root) return;
    const el = root.querySelector<HTMLButtonElement>("[data-testid='indicators_menu_button']");
    if (!el) return;
    const handler = () => onIndicators?.();
    el.addEventListener('click', handler);
    return () => el.removeEventListener('click', handler);
  }, [domReady, onIndicators]);

  // Interactivity: onLockScale -> testid="display_options_lock_scale_toggle" (click)
  useEffect(() => {
    if (!domReady) return;
    const root = rootRef.current;
    if (!root) return;
    const el = root.querySelector<HTMLButtonElement>("[data-testid='display_options_lock_scale_toggle']");
    if (!el) return;
    const handler = () => onLockScale?.();
    el.addEventListener('click', handler);
    return () => el.removeEventListener('click', handler);
  }, [domReady, onLockScale]);

  return (
    <div
      ref={rootRef}
      style={{ width: '100%', height: '100%' }}
      suppressHydrationWarning
    />
  );
}
