'use client';
import { useEffect, useRef, useState } from 'react';
import { PIXEL_RECENT_ORDERS_HTML } from './PixelRecentOrders-dom';

// AUTO-GENERATED by cloner/src/lib/pixel_render_clone.mjs.
// Captured HTML lives in ./PixelRecentOrders-dom.ts.
// Source URI: rendered_dom.html @ WIDGET_TYPE_RECENT_ORDERS_TABLE
// Render-to-match pattern: production CSS styles production DOM, so we
// inject it via innerHTML once (NOT dangerouslySetInnerHTML, which would
// blow away anything we mount inside the subtree on every re-render).

type Props = Record<string, never>;

export function PixelRecentOrders() {
  
  const rootRef = useRef<HTMLDivElement | null>(null);
  const [domReady, setDomReady] = useState(false);

  // Inject the captured DOM exactly once.
  useEffect(() => {
    if (!rootRef.current) return;
    if (rootRef.current.innerHTML === '') {
      rootRef.current.innerHTML = PIXEL_RECENT_ORDERS_HTML;
    }
    setDomReady(true);
  }, []);

  // The capture was taken on a paper account with no orders, so the rowgroup
  // is empty. Append realistic AMD/NVDA/AAPL option orders so the panel
  // renders populated. We size each cell from the same CSS vars the header
  // uses (--column-width-RECENT_ORDERS_COLUMN_NAME_*) for layout parity.
  useEffect(() => {
    if (!domReady || !rootRef.current) return;
    const root = rootRef.current;
    const rowgroup = root.querySelector<HTMLElement>('[role="rowgroup"]');
    if (!rowgroup || rowgroup.querySelector('[role="row"]')) return;

    // Hide the captured "Open orders will appear here..." empty-state block.
    // The placeholder span lives inside a div with an SVG sibling + spacer.
    // Hide the span's parent (the icon+text+spacer wrapper).
    Array.from(root.querySelectorAll('span')).forEach((sp) => {
      if (sp.textContent?.includes('Open orders will appear here')) {
        const wrap = sp.parentElement;
        if (wrap) wrap.style.display = 'none';
      }
    });

    // Widen Bid/Ask/Limit so populated dollar amounts fit without truncation,
    // and Instrument so "AMD 5/15 $400 Call" fits. Captured widths assume
    // short pre-market values — override on both header and rowgroup so they
    // stay aligned.
    const widthOverrides: Record<string, string> = {
      '--column-width-RECENT_ORDERS_COLUMN_NAME_INSTRUMENT': '140px',
      '--column-width-RECENT_ORDERS_COLUMN_NAME_LIMIT_PRICE': '64px',
      '--column-width-RECENT_ORDERS_COLUMN_NAME_BID_PRICE': '60px',
      '--column-width-RECENT_ORDERS_COLUMN_NAME_ASK_PRICE': '60px',
      '--column-width-RECENT_ORDERS_COLUMN_NAME_AVERAGE_FILL_PRICE': '78px',
    };
    const header = root.querySelector<HTMLElement>('[data-testid="table-header"]');
    [header, rowgroup].forEach((el) => {
      if (!el) return;
      for (const [k, v] of Object.entries(widthOverrides)) el.style.setProperty(k, v);
    });
    // Zero the trailing virtual-padding spacers. The capture baked in
    // --virtual-padding-right: 317px inline on the rowgroup/header AND
    // separate spacer divs sized to that var sit as siblings of the row, so
    // cascading the var alone doesn't reach them. Set inline-size directly.
    Array.from(
      root.querySelectorAll<HTMLElement>('[class*="inline-size_var(--virtual-padding"]')
    ).forEach((el) => {
      el.style.inlineSize = '0px';
    });

    // Append synthetic header cells for the 4 columns missing from the
    // capture (Submitted/Updated/Avg Fill/Filled Qty were clipped off the
    // right at capture time). The captured header is CSS Grid with
    // `grid-auto-flow: column` — new children become new grid columns
    // automatically, so we insert directly into the grid container BEFORE
    // the trailing virtual-padding spacer (last child).
    if (header) {
      const grid = header.querySelector<HTMLElement>('.display_grid');
      if (grid && grid.querySelectorAll('[role="columnheader"]').length < 11) {
        const synth = (colId: string, label: string, align: 'start' | 'end' = 'start') => {
          const el = document.createElement('div');
          el.setAttribute('role', 'columnheader');
          el.setAttribute('data-header-column-id', colId);
          el.style.cssText = `
            inline-size: var(--column-width-${colId});
            display: flex;
            align-items: center;
            justify-content: flex-${align};
            padding-inline: 8px;
            block-size: 40px;
            color: rgba(255,255,255,0.55);
            font: 600 12px/1 var(--bw-ds--font-family);
            letter-spacing: -0.01em;
          `;
          el.textContent = label;
          return el;
        };
        const spacer = grid.lastElementChild; // trailing virtual-padding spacer
        const cells = [
          synth('RECENT_ORDERS_COLUMN_NAME_SUBMITTED', 'Submitted'),
          synth('RECENT_ORDERS_COLUMN_NAME_UPDATED', 'Updated'),
          synth('RECENT_ORDERS_COLUMN_NAME_AVERAGE_FILL_PRICE', 'Avg Fill', 'end'),
          synth('RECENT_ORDERS_COLUMN_NAME_FILLED_QUANTITY', 'Filled Qty', 'end'),
        ];
        cells.forEach((c) => grid.insertBefore(c, spacer));
      }
    }

    const POSITIVE = '#00C805';
    const NEGATIVE = '#FF5000';
    const FG1 = 'rgba(255,255,255,0.95)';
    const FG3 = 'rgba(255,255,255,0.55)';

    type Order = {
      instrument: string;
      status: 'Filled' | 'Open' | 'Canceled';
      side: 'Buy' | 'Sell';
      type: 'Limit' | 'Market';
      qty: string;
      limit: string;
      bid: string;
      ask: string;
      submitted: string;
      updated: string;
      avgFill: string;
      filledQty: string;
    };

    const orders: Order[] = [
      { instrument: 'AMD 5/8 $392.5 Call', status: 'Filled', side: 'Buy',  type: 'Limit', qty: '1', limit: '$62.95', bid: '$62.85', ask: '$63.05', submitted: '12:34:21', updated: '12:34:22', avgFill: '$62.20', filledQty: '1' },
      { instrument: 'AMD 5/8 $392.5 Call', status: 'Filled', side: 'Buy',  type: 'Limit', qty: '2', limit: '$58.00', bid: '$57.90', ask: '$58.15', submitted: '11:02:08', updated: '11:02:09', avgFill: '$57.85', filledQty: '2' },
      { instrument: 'NVDA 5/8 $1100 Call', status: 'Open',   side: 'Sell', type: 'Limit', qty: '1', limit: '$14.50', bid: '$14.10', ask: '$14.55', submitted: '10:48:33', updated: '10:48:33', avgFill: '—',     filledQty: '0' },
      { instrument: 'AMD 5/15 $400 Call',  status: 'Canceled', side: 'Buy', type: 'Limit', qty: '3', limit: '$31.20', bid: '$30.85', ask: '$31.35', submitted: '10:01:55', updated: '10:02:40', avgFill: '—',     filledQty: '0' },
      { instrument: 'AAPL 5/22 $200 Put',  status: 'Filled', side: 'Buy',  type: 'Limit', qty: '1', limit: '$4.05',  bid: '$4.00',  ask: '$4.10',  submitted: '09:55:14', updated: '09:55:14', avgFill: '$4.05',  filledQty: '1' },
      { instrument: 'TSLA 5/15 $180 Put',  status: 'Filled', side: 'Sell', type: 'Limit', qty: '2', limit: '$3.45',  bid: '$3.40',  ask: '$3.50',  submitted: '09:42:01', updated: '09:42:02', avgFill: '$3.45',  filledQty: '2' },
      { instrument: 'AMD 5/8 $400 Call',   status: 'Filled', side: 'Buy',  type: 'Market', qty: '1', limit: '—',      bid: '$45.20', ask: '$45.60', submitted: '09:31:14', updated: '09:31:14', avgFill: '$45.55', filledQty: '1' },
      { instrument: 'SPY 5/30 $570 Call',  status: 'Open',   side: 'Buy',  type: 'Limit', qty: '5', limit: '$2.10',  bid: '$2.05',  ask: '$2.12',  submitted: '09:30:45', updated: '09:30:45', avgFill: '—',     filledQty: '0' },
    ];

    const sideColor = (s: Order['side']) => (s === 'Buy' ? POSITIVE : NEGATIVE);
    const statusColor = (s: Order['status']) =>
      s === 'Filled' ? POSITIVE : s === 'Canceled' ? FG3 : FG1;

    const cell = (
      colId: string,
      text: string,
      opts: { color?: string; align?: 'start' | 'end'; bold?: boolean } = {}
    ) => {
      const align = opts.align ?? 'start';
      const color = opts.color ?? FG1;
      const weight = opts.bold ? '600' : '400';
      return `<div role="gridcell" style="
        inline-size: var(--column-width-${colId});
        flex: 0 0 auto;
        display: flex;
        align-items: center;
        justify-content: flex-${align};
        padding-inline: 8px;
        block-size: 32px;
        color: ${color};
        font: ${weight} 12px/1 Phonic, 'Phonic Variable', ui-monospace, monospace;
        font-variant-numeric: tabular-nums;
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
      ">${text}</div>`;
    };

    const rowHtml = (o: Order, i: number) => `
      <div role="row" data-row-index="${i}" style="
        display: flex;
        flex-direction: row;
        align-items: center;
        block-size: 32px;
        border-block-end: 1px solid rgba(255,255,255,0.04);
        background-color: ${i % 2 === 0 ? 'transparent' : 'rgba(255,255,255,0.015)'};
        cursor: pointer;
      "
      onmouseover="this.style.backgroundColor='rgba(255,255,255,0.05)'"
      onmouseout="this.style.backgroundColor='${i % 2 === 0 ? 'transparent' : 'rgba(255,255,255,0.015)'}'">
        ${cell('RECENT_ORDERS_COLUMN_NAME_INSTRUMENT', o.instrument, { bold: true })}
        ${cell('RECENT_ORDERS_COLUMN_NAME_STATUS', o.status, { color: statusColor(o.status) })}
        ${cell('RECENT_ORDERS_COLUMN_NAME_SIDE', o.side, { color: sideColor(o.side), bold: true })}
        ${cell('RECENT_ORDERS_COLUMN_NAME_TYPE', o.type)}
        ${cell('RECENT_ORDERS_COLUMN_NAME_ORDER_QUANTITY', o.qty, { align: 'end' })}
        ${cell('RECENT_ORDERS_COLUMN_NAME_LIMIT_PRICE', o.limit, { align: 'end' })}
        ${cell('RECENT_ORDERS_COLUMN_NAME_BID_PRICE', o.bid, { align: 'end', color: FG3 })}
        ${cell('RECENT_ORDERS_COLUMN_NAME_ASK_PRICE', o.ask, { align: 'end', color: FG3 })}
        ${cell('RECENT_ORDERS_COLUMN_NAME_SUBMITTED', o.submitted, { color: FG3 })}
        ${cell('RECENT_ORDERS_COLUMN_NAME_UPDATED', o.updated, { color: FG3 })}
        ${cell('RECENT_ORDERS_COLUMN_NAME_AVERAGE_FILL_PRICE', o.avgFill, { align: 'end' })}
        ${cell('RECENT_ORDERS_COLUMN_NAME_FILLED_QUANTITY', o.filledQty, { align: 'end' })}
      </div>
    `;

    const body = document.createElement('div');
    body.style.display = 'flex';
    body.style.flexDirection = 'column';
    body.innerHTML = orders.map((o, i) => rowHtml(o, i)).join('');
    rowgroup.appendChild(body);
  }, [domReady]);


  return (
    <div
      ref={rootRef}
      style={{ width: '100%', height: '100%' }}
      suppressHydrationWarning
    />
  );
}
