'use client';
import { useEffect, useRef, useState } from 'react';
import { PIXEL_INSTRUMENT_DETAIL_HTML } from './PixelInstrumentDetail-dom';

// AUTO-GENERATED by cloner/src/lib/pixel_render_clone.mjs.
// Captured HTML lives in ./PixelInstrumentDetail-dom.ts.
// Source URI: requested-0f055.html @ WIDGET_TYPE_SNAPSHOT
// Render-to-match pattern: production CSS styles production DOM, so we
// inject it via innerHTML once (NOT dangerouslySetInnerHTML, which would
// blow away anything we mount inside the subtree on every re-render).

type Props = {
  onBuy?: () => void;
  onSell?: () => void;
};

export function PixelInstrumentDetail(props: Props) {
  const {
    onBuy,
    onSell,
  } = props;
  const rootRef = useRef<HTMLDivElement | null>(null);
  const [domReady, setDomReady] = useState(false);

  // Inject the captured DOM exactly once.
  useEffect(() => {
    if (!rootRef.current) return;
    if (rootRef.current.innerHTML === '') {
      rootRef.current.innerHTML = PIXEL_INSTRUMENT_DETAIL_HTML;
    }
    setDomReady(true);
  }, []);

  // Interactivity: onBuy -> testid="legend_trade_button.buy" (click)
  useEffect(() => {
    if (!domReady) return;
    const root = rootRef.current;
    if (!root) return;
    const el = root.querySelector<HTMLButtonElement>("[data-testid='legend_trade_button.buy']");
    if (!el) return;
    const handler = () => onBuy?.();
    el.addEventListener('click', handler);
    return () => el.removeEventListener('click', handler);
  }, [domReady, onBuy]);

  // Interactivity: onSell -> testid="legend_trade_button.sell" (click)
  useEffect(() => {
    if (!domReady) return;
    const root = rootRef.current;
    if (!root) return;
    const el = root.querySelector<HTMLButtonElement>("[data-testid='legend_trade_button.sell']");
    if (!el) return;
    const handler = () => onSell?.();
    el.addEventListener('click', handler);
    return () => el.removeEventListener('click', handler);
  }, [domReady, onSell]);

  return (
    <div
      ref={rootRef}
      style={{ width: '100%', height: '100%' }}
      suppressHydrationWarning
    />
  );
}
