'use client';
import { useEffect, useRef, useState } from 'react';
import { PIXEL_OPTIONS_CHAIN_HTML } from './PixelOptionsChain-dom';

// AUTO-GENERATED by cloner/src/lib/pixel_render_clone.mjs.
// Captured HTML lives in ./PixelOptionsChain-dom.ts.
// Source URI: requested-0f055.html @ WIDGET_TYPE_OPTION_CHAIN
// Render-to-match pattern: production CSS styles production DOM, so we
// inject it via innerHTML once (NOT dangerouslySetInnerHTML, which would
// blow away anything we mount inside the subtree on every re-render).

type Props = {
  onSymbolClick?: () => void;
  onPLClick?: () => void;
};

export function PixelOptionsChain(props: Props) {
  const {
    onSymbolClick,
    onPLClick,
  } = props;
  const rootRef = useRef<HTMLDivElement | null>(null);
  const [domReady, setDomReady] = useState(false);

  // Inject the captured DOM exactly once.
  useEffect(() => {
    if (!rootRef.current) return;
    if (rootRef.current.innerHTML === '') {
      rootRef.current.innerHTML = PIXEL_OPTIONS_CHAIN_HTML;
    }
    setDomReady(true);
  }, []);

  // Flatten react-virtual's persisted padding so rows are visible at the top.
  // The captured DOM has --focused-chain-virtual-padding-top: 2640px baked in
  // (from when the user had scrolled mid-chain during capture).
  useEffect(() => {
    if (!domReady) return;
    const root = rootRef.current;
    if (!root) return;
    const body = root.querySelector<HTMLElement>("[data-testid='focused-chain-body-container']");
    if (body) {
      body.style.setProperty('--focused-chain-virtual-padding-top', '0px');
      body.style.setProperty('--focused-chain-virtual-padding-bottom', '0px');
    }
  }, [domReady]);

  // Interactivity: onSymbolClick -> testid="instrument-marquee-button" (click)
  useEffect(() => {
    if (!domReady) return;
    const root = rootRef.current;
    if (!root) return;
    const el = root.querySelector<HTMLButtonElement>("[data-testid='instrument-marquee-button']");
    if (!el) return;
    const handler = () => onSymbolClick?.();
    el.addEventListener('click', handler);
    return () => el.removeEventListener('click', handler);
  }, [domReady, onSymbolClick]);

  // Interactivity: onPLClick -> testid="metrics-panel-estimated-pl" (click)
  useEffect(() => {
    if (!domReady) return;
    const root = rootRef.current;
    if (!root) return;
    const el = root.querySelector<HTMLElement>("[data-testid='metrics-panel-estimated-pl']");
    if (!el) return;
    const handler = () => onPLClick?.();
    el.addEventListener('click', handler);
    return () => el.removeEventListener('click', handler);
  }, [domReady, onPLClick]);

  return (
    <div
      ref={rootRef}
      style={{ width: '100%', height: '100%' }}
      suppressHydrationWarning
    />
  );
}
