'use client';
import { useEffect, useRef, useState } from 'react';
import { PIXEL_ORDER_BOOK_GEN_HTML } from './PixelOrderBookGen-dom';

// AUTO-GENERATED by cloner/src/lib/pixel_render_clone.mjs.
// Captured HTML lives in ./PixelOrderBookGen-dom.ts.
// Source URI: robinhood-legend-options reversed/dom-slices/orderbook.html @ ladder-chart-container
// Render-to-match pattern: production CSS styles production DOM, so we
// inject it via innerHTML once (NOT dangerouslySetInnerHTML, which would
// blow away anything we mount inside the subtree on every re-render).

type Props = {
  onBuy?: () => void;
  onSell?: () => void;
  onQtyDecrement?: () => void;
  onQtyIncrement?: () => void;
  onOverlayClick?: () => void;
};

export function PixelOrderBookGen(props: Props) {
  const {
    onBuy,
    onSell,
    onQtyDecrement,
    onQtyIncrement,
    onOverlayClick,
  } = props;
  const rootRef = useRef<HTMLDivElement | null>(null);
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const [domReady, setDomReady] = useState(false);

  // Inject the captured DOM exactly once.
  useEffect(() => {
    if (!rootRef.current) return;
    if (rootRef.current.innerHTML === '') {
      rootRef.current.innerHTML = PIXEL_ORDER_BOOK_GEN_HTML;
    }
    setDomReady(true);
  }, []);

  // Optional canvas mount: inject a <canvas> inside the captured DOM at the
  // configured selector. Re-mounts on prop changes that would re-run this
  // effect (none by default). Consumers can grab canvasRef.current to draw.
  useEffect(() => {
    if (!domReady || !rootRef.current) return;
    const area = rootRef.current.querySelector<HTMLElement>("[data-element=\"canvasArea\"]");
    if (!area) return;
    const canvas = document.createElement('canvas');
    canvas.style.position = 'absolute';
    canvas.style.inset = '0';
    canvas.style.width = '100%';
    canvas.style.height = '100%';
    canvas.style.touchAction = 'manipulation';
    area.appendChild(canvas);
    canvasRef.current = canvas;
    return () => {
      canvas.remove();
      canvasRef.current = null;
    };
  }, [domReady]);
  // Interactivity: onBuy -> testid="ladder.header.equity.button.buy.buy" (click)
  useEffect(() => {
    if (!domReady) return;
    const root = rootRef.current;
    if (!root) return;
    const el = root.querySelector<HTMLButtonElement>("[data-testid='ladder.header.equity.button.buy.buy']");
    if (!el) return;
    const handler = () => onBuy?.();
    el.addEventListener('click', handler);
    return () => el.removeEventListener('click', handler);
  }, [domReady, onBuy]);

  // Interactivity: onSell -> testid="ladder.header.equity.button.sell.sell" (click)
  useEffect(() => {
    if (!domReady) return;
    const root = rootRef.current;
    if (!root) return;
    const el = root.querySelector<HTMLButtonElement>("[data-testid='ladder.header.equity.button.sell.sell']");
    if (!el) return;
    const handler = () => onSell?.();
    el.addEventListener('click', handler);
    return () => el.removeEventListener('click', handler);
  }, [domReady, onSell]);

  // Interactivity: onQtyDecrement -> testid="undefined-stepper-decrement" (click)
  useEffect(() => {
    if (!domReady) return;
    const root = rootRef.current;
    if (!root) return;
    const el = root.querySelector<HTMLButtonElement>("[data-testid='undefined-stepper-decrement']");
    if (!el) return;
    const handler = () => onQtyDecrement?.();
    el.addEventListener('click', handler);
    return () => el.removeEventListener('click', handler);
  }, [domReady, onQtyDecrement]);

  // Interactivity: onQtyIncrement -> testid="undefined-stepper-increment" (click)
  useEffect(() => {
    if (!domReady) return;
    const root = rootRef.current;
    if (!root) return;
    const el = root.querySelector<HTMLButtonElement>("[data-testid='undefined-stepper-increment']");
    if (!el) return;
    const handler = () => onQtyIncrement?.();
    el.addEventListener('click', handler);
    return () => el.removeEventListener('click', handler);
  }, [domReady, onQtyIncrement]);

  // Interactivity: onOverlayClick -> testid="buy-order-button" (click)
  useEffect(() => {
    if (!domReady) return;
    const root = rootRef.current;
    if (!root) return;
    const el = root.querySelector<HTMLButtonElement>("[data-testid='buy-order-button']");
    if (!el) return;
    const handler = () => onOverlayClick?.();
    el.addEventListener('click', handler);
    return () => el.removeEventListener('click', handler);
  }, [domReady, onOverlayClick]);

  return (
    <div
      ref={rootRef}
      style={{ width: '100%', height: '100%' }}
      suppressHydrationWarning
    />
  );
}
