'use client';
import { useEffect, useRef, useState } from 'react';
import { PIXEL_POSITIONS_TABLE_HTML } from './PixelPositionsTable-dom';

// AUTO-GENERATED by cloner/src/lib/pixel_render_clone.mjs.
// Captured HTML lives in ./PixelPositionsTable-dom.ts.
// Source URI: rendered_dom.html @ WIDGET_TYPE_POSITIONS_TABLE
// Render-to-match pattern: production CSS styles production DOM, so we
// inject it via innerHTML once (NOT dangerouslySetInnerHTML, which would
// blow away anything we mount inside the subtree on every re-render).

type Props = Record<string, never>;

export function PixelPositionsTable() {
  
  const rootRef = useRef<HTMLDivElement | null>(null);
  const [domReady, setDomReady] = useState(false);

  // Inject the captured DOM exactly once.
  useEffect(() => {
    if (!rootRef.current) return;
    if (rootRef.current.innerHTML === '') {
      rootRef.current.innerHTML = PIXEL_POSITIONS_TABLE_HTML;
    }
    setDomReady(true);
  }, []);


  return (
    <div
      ref={rootRef}
      style={{ width: '100%', height: '100%' }}
      suppressHydrationWarning
    />
  );
}
