import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";

export default function Terms() {
  return (
    <div className="flex flex-col gap-5 max-h-[65vh] overflow-y-auto pr-1">
      <Link
        to="/"
        className="flex items-center gap-1 text-sm text-gray-500 hover:text-gray-700"
      >
        <ArrowLeft className="h-3.5 w-3.5" />
        Back
      </Link>

      <div>
        <h2 className="text-xl font-bold text-gray-900">Terms of Use</h2>
        <p className="mt-1 text-[11px] text-gray-400">
          Last updated: March 2026
        </p>
      </div>

      <div className="flex flex-col gap-4 text-[13px] leading-relaxed text-gray-600">
        <section>
          <h3 className="mb-1 text-sm font-semibold text-gray-800">
            Research &amp; Educational Use Only
          </h3>
          <p>
            DailyIQ is provided strictly for research,
            educational, and analytical purposes. It is not a financial
            advisory service and does not constitute investment advice,
            solicitation, or recommendation to buy or sell any securities.
          </p>
        </section>

        <section>
          <h3 className="mb-1 text-sm font-semibold text-gray-800">
            No Guarantee of Results
          </h3>
          <p>
            Past performance is not indicative of future results. Backtesting
            and simulated trading results are hypothetical and have inherent
            limitations. No representation is made that any account will or is
            likely to achieve profits or losses similar to those shown.
          </p>
        </section>

        <section>
          <h3 className="mb-1 text-sm font-semibold text-gray-800">
            Model &amp; Data Risks
          </h3>
          <p>
            Machine learning models trained on historical market data are
            subject to significant risks including, but not limited to:
          </p>
          <ul className="mt-1.5 ml-4 flex flex-col gap-1 list-disc">
            <li>
              <span className="font-medium text-gray-700">Overfitting</span> —
              models may learn noise and patterns specific to training data
              that do not generalize to live markets.
            </li>
            <li>
              <span className="font-medium text-gray-700">Underfitting</span> —
              models may fail to capture meaningful market dynamics, producing
              unreliable signals.
            </li>
            <li>
              <span className="font-medium text-gray-700">Survivorship bias</span> —
              historical datasets may exclude delisted or failed securities,
              skewing results.
            </li>
            <li>
              <span className="font-medium text-gray-700">Look-ahead bias</span> —
              strategies may inadvertently incorporate future information not
              available at the time of the simulated trade.
            </li>
            <li>
              <span className="font-medium text-gray-700">Regime change</span> —
              market conditions evolve; a model trained on past regimes may
              perform poorly under new conditions.
            </li>
          </ul>
        </section>

        <section>
          <h3 className="mb-1 text-sm font-semibold text-gray-800">
            Paper Trading Only
          </h3>
          <p>
            Version 1 of DailyIQ supports paper trading
            only through Interactive Brokers TWS. No real order routing is
            performed. Users assume all risk if they choose to act on any
            signals, strategies, or outputs generated by this software.
          </p>
        </section>

        <section>
          <h3 className="mb-1 text-sm font-semibold text-gray-800">
            Data Privacy
          </h3>
          <p>
            All market data, ML model weights, strategy configurations, and
            workspace preferences are stored locally on your device. We do not
            upload, transmit, or store your trading data on any external
            server. Supabase is used exclusively for authentication.
          </p>
        </section>

        <section>
          <h3 className="mb-1 text-sm font-semibold text-gray-800">
            Limitation of Liability
          </h3>
          <p>
            In no event shall DailyIQ or its contributors be liable for any
            direct, indirect, incidental, special, or consequential damages
            arising from the use of this software, including but not limited to
            financial losses from trading decisions informed by backtesting
            results or model outputs.
          </p>
        </section>

        <p className="text-[11px] text-gray-400 pt-2 border-t border-gray-100">
          By using DailyIQ, you acknowledge that you have
          read, understood, and agreed to these terms.
        </p>
      </div>
    </div>
  );
}
